version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "3.0-buster"
        NODE_VERSION: "16"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
